name: Release New Version

on:
  release:
    types: [released]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Bootstrap
      uses: ./.github/actions/bootstrap

    - name: Get artifacts and publish
      env:
        GITHUB_REF: ${{ github.ref }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}" | cut -c2-)

        wheel_name="flwr-${TAG_NAME}-py3-none-any.whl"        
        tar_name="flwr-${TAG_NAME}.tar.gz"

        wheel_url="https://artifact.flower.dev/py/release/v${TAG_NAME}/${wheel_name}"
        tar_url="https://artifact.flower.dev/py/release/v${TAG_NAME}/${tar_name}"
        
        echo $wheel_url
        echo $tar_url

        curl $wheel_url --output $wheel_name
        curl $tar_url --output $tar_name

        python -m poetry publish -u __token__ -p $PYPI_TOKEN
