name: Release Framework

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download wheel
        run: |
            tag_name=$(echo "${GITHUB_REF_NAME}" | cut -c2-)
            
            wheel_name="flwr-${tag_name}-py3-none-any.whl"
            echo "WHEEL_NAME=$wheel_name" >> "$GITHUB_ENV"
            echo $wheel_name
            
            tar_name="flwr-${tag_name}.tar.gz"
            echo "TAR_NAME=$tar_name" >> "$GITHUB_ENV"
            echo $tar_name

            wheel_url="https://artifact.flower.dev/py//${GITHUB_SHA::7}/${wheel_name}"
            echo $wheel_url
            curl $wheel_url --output $wheel_name

            tar_url="https://artifact.flower.dev/py//${GITHUB_SHA::7}/${tar_name}"
            echo $tar_url
            curl $tar_url --output $tar_name
      - name: Generate body
        run: echo "BODY=$(./dev/get-latest-changelog.sh)" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${BODY}
          draft: true
          files: |
            ${WHEEL_NAME}
            ${TAR_NAME}
