name: Translations

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows to manually trigger the workflow

jobs:
  update-and-pr:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    env:
      branch-name: auto-update-trans-text
    name: Update text
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m poetry install
          pip install sphinx==7.2.0

      - name: Update text and translations for all locales
        run: |
          cd doc
          make update-text
          for langDir in locales/*; do
            if [ -d "$langDir" ]; then
              lang=$(basename $langDir)
              echo "Updating language $lang"
              make update-lang lang=$lang
            fi
          done

      - name: Commit changes
        id: commit_changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add doc/locales
          git commit -m "Update text and language files" || echo "::set-output name=changes::false"
          echo "::set-output name=changes::true"
        continue-on-error: true

      - name: Push changes
        if: steps.commit_changes.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: '${{ env.branch-name }}'

      - name: Create Pull Request
        if: steps.commit_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: '${{ env.branch-name }}'
          delete-branch: true
          title: 'docs(framework:skip) Update source texts for translations (automated)'
          body: 'This PR is auto-generated to update text and language files.'
          draft: false
